# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/environment-variables
name: push-image
on:
  push:
    paths-ignore:
      - .github/*
  workflow_dispatch:
    inputs:
      major_version_number:
        description: Basis for semantic version number
        required: false
        default: '0.0'
env:
  IMAGE_NAME: ghcr.io/${{github.repository}}
  SEMANTIC_VERSION: ${{ github.event.inputs.major_version_number }}.$GITHUB_RUN_NUMBER 
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
jobs:
  push-image-job:
    runs-on: ubuntu-latest # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
      - shell: bash {0} # try to pull image if available
        continue-on-error: true
        run: sudo docker pull $IMAGE_NAME:$GITHUB_REF_NAME-latest
      - run: |
          sudo docker build $GITHUB_WORKSPACE \
          --build-arg BUILD_COMMIT=$GITHUB_SHA \
          --tag $IMAGE_NAME:$GITHUB_SHA \
          --tag $IMAGE_NAME:$SEMANTIC_VERSION \
          --tag $IMAGE_NAME:$GITHUB_REF_NAME-latest \
          --cache-from $IMAGE_NAME:$GITHUB_REF_NAME-latest
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          sudo docker push $IMAGE_NAME --all-tags
      - if: $GITHUB_REF_NAME == ${{ github.event.repository.default_branch }}
        run: |
          git tag $SEMANTIC_VERSION
          git push origin $SEMANTIC_VERSION
