# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/environment-variables
name: push-image
on: # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
  push:
    paths:
      - Dockerfile
      - go.mod
      - pkg/**
  workflow_dispatch:
    inputs:
      manual-workflow-comment:
        description: Manual workflow_dispatch needs at least one input parameter. Use this for comments on the reason for running the workflow manually.
        required: false
        default: Manual workflow_dispatch trigger
env:
  IMAGE_NAME: ghcr.io/${{github.repository}}
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
jobs:
  build-tag-push:
    runs-on: ubuntu-latest # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
      - id: build
        run: sudo docker build $GITHUB_WORKSPACE --build-arg BUILD_COMMIT=$GITHUB_SHA --tag $IMAGE_NAME:$GITHUB_SHA --tag $IMAGE_NAME:$GITHUB_REF_NAME-latest
      - id: tag
        if: github.ref_name == github.event.repository.default_branch
        run: |
          export SEMANTIC_VERSION=0.0.$GITHUB_RUN_NUMBER
          sudo docker tag $IMAGE_NAME:$GITHUB_SHA $IMAGE_NAME:$SEMANTIC_VERSION
          sudo docker tag $IMAGE_NAME:$GITHUB_SHA $IMAGE_NAME:latest
          git tag $SEMANTIC_VERSION
          git push origin $SEMANTIC_VERSION
      - id: push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          sudo docker push $IMAGE_NAME --all-tags
